name: Deploy Dev API

on:
  push:
    branches:
      - dev

env:
    PORT: "8085"
    IMAGE_NAME: schedule-dev-api

jobs:
  BuildAndDeployDev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -f ScheduleApi/Dockerfile -t $IMAGE_NAME .

    - name: Save Docker image to tarball
      run: |
        docker save $IMAGE_NAME > $IMAGE_NAME.tar

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/github_deploy
        chmod 600 ~/.ssh/github_deploy
        ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

    - name: Upload Docker image to server
      run: |
        scp -i ~/.ssh/github_deploy $IMAGE_NAME.tar ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}

    - name: Deploy on server
      run: |
        ssh -i ~/.ssh/github_deploy ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}
          docker load < ${{ secrets.DEPLOY_PATH }}/$IMAGE_NAME.tar
          docker stop $IMAGE_NAME || true
          docker rm $IMAGE_NAME || true
          docker run -d --name $IMAGE_NAME --restart always -p $PORT:8080 $IMAGE_NAME
        EOF