name: Deploy Dev API

on:
  push:
    branches:
      - dev

env:
  IMAGE_NAME: schedule-dev-api
  DOCKERFILE_PATH: ScheduleApi/Dockerfile
  DEPLOY_PORT: 8085


jobs:
  BuildAndDeployDev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME .

    - name: Save Docker image to tarball
      run: docker save $IMAGE_NAME > $IMAGE_NAME.tar

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Upload Docker image
      run: -i ~/.ssh/github_deploy |
          scp $IMAGE_NAME.tar ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}


    - name: Deploy on server
      run: |
        ssh -i ~/.ssh/github_deploy ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << EOF
          docker load < ${{ secrets.DEPLOY_PATH }}/$IMAGE_NAME.tar
          docker stop $IMAGE_NAME || true
          docker rm $IMAGE_NAME || true
          docker run -d --name $IMAGE_NAME --restart always -p $DEPLOY_PORT:8080 $IMAGE_NAME
        EOF